# Place this file in .github/workflows/prod-guard.yml in your repository
name: Change Assurance Window - Production Guard

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce-ca:
    uses: beckyshaw/change-assurance-window/.github/workflows/enforce-change-assurance.yml@v1
    with:
      windows_file: change-windows.yml # this file is to be created in the .github/ of your repo
      timezone: UTC # Replace with your desired timezone if needed
